### ISSUE TITLE
Не сравнивайте double через assertEquals

### ISSUE THREAD

**Issue by coursar** [NailMukhametshin/CreditService#2]
https://github.com/NailMukhametshin/CreditService/blob/4fe3961e08a0d4008e62cbf4b9b834369334d5b1/src/test/java/ru/itpark/CreditServiceTest.java#L11-L12

**Comment by NailMukhametshin** [comment]
@coursar, исправил в 92029f0ef20bbb4bec6d3615992cde46c7c22276
