### ISSUE TITLE
Какой смысл несёт имя v?

### ISSUE THREAD

**Issue by coursar** [NailMukhametshin/CreditService#3]
https://github.com/NailMukhametshin/CreditService/blob/4fe3961e08a0d4008e62cbf4b9b834369334d5b1/src/test/java/ru/itpark/CreditServiceTest.java#L17

**Comment by NailMukhametshin** [comment]
@coursar, сделал в a430d27cf2beaafd0a2ac5dc85ccfcc248ebbc49
